### ISSUE TITLE
HUE_BASE

### ISSUE THREAD

**Issue by MyeongGiHan** [mojosoeun/smart-mirror-ko#6]
안녕하세요. 몇일안되서 연락드렸네요... 염치없지만... 

HUE_BASE는 어떤건지 인터넷에 치고 찾아봐도 잘 모르겠어서요...

말씀하신데로 issue에 등록했습니다. 연락드리는거 불편해 하실것 같아서요~

찾아보는 노력은 하고 열심히 공부하고있습니다. ㅠㅠㅠ 

그냥 물어보기만 한다고 생각은 말아주시길...

**Comment by mojosoeun** [comment]
안녕하세요. 답변이 늦었네요. 
config.js 파일에 있는 변수 HUE_BASE란 philips hue 전등을 제어하는데 사용되는 ip주소와 api_key 값입니다. 
만약 HUE_BASE를 사용하시려면 philips hue 전등을 따로 프리스비에서 구매 하셔야 합니다. 
그렇지 않으면 HUE_BASE와 관련된 코드를 제거하시고 커스터마이징 하셔서 사용하시면 됩니다. 
감사합니다.
