### ISSUE TITLE
음... 다 됬는데 작동도 되는데 하나 오류가 몇일째 찾아도 뭔지 감이 안잡혀서요....

### ISSUE THREAD

**Issue by MyeongGiHan** [mojosoeun/smart-mirror-ko#7]
logging.h 파일의 779번째 라인에서 오류나는거 같은데 제 라즈베리파이에는 이런 파일이 없고 인터넷 찾아도 이상한 파일만 나와서요

혹시 아시나 해서요... 귀찮게 안하려고 하는데;; 궁금증이 너무 많아서 ㅠㅠ

![2016-04-07-223709_1440x900_scrot](https://cloud.githubusercontent.com/assets/18199920/14353064/6bd651b6-fd12-11e5-8444-1b8b46e80f5d.png)

**Comment by mojosoeun** [comment]
Chromium문제 같네요.
해당 프로젝트를 지웠다 다시 깔아보세요.

**Comment by mojosoeun** [comment]
http://askubuntu.com/questions/596994/nm-applet-gives-errors 이거 참고해 보세요.

**Comment by MyeongGiHan** [comment]
지웠다깔아도 같은것 같아서요~ 크로미움을 지우고 다시해보던지 해보려고 합니다.

**Comment by mojosoeun** [comment]
크로미니움 문제가 아닌거 같습니다.
http://askubuntu.com/questions/596994/nm-applet-gives-errors  
이 링크로 했더니 해결 했다는 얘기가 있네요. 꼭 시도 하셔서 오류 해결하셨으면 좋겠네요. 
![2016-04-10 9 19 49](https://cloud.githubusercontent.com/assets/4694139/14410140/05f3cdb8-ff62-11e5-8866-668049482e9f.png)

**Comment by MyeongGiHan** [comment]
정신없어서 지금 보았네요~ 오늘가서 해보겠습니다.

신경써주셔서 감사합니다.~ 좋은하루 되세요~ ㅎㅎㅎ

**Comment by mojosoeun** [comment]
dddddd
